"""add google places fields to events

Revision ID: 21be0b09c373
Revises: b8a4b3c5962b
Create Date: 2025-08-12 15:38:26.276351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21be0b09c373'
down_revision = 'b8a4b3c5962b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('place_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('place_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('place_address', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('place_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('place_lng', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('place_types', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('place_website', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('place_maps_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('place_price_level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('place_street_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('place_route', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('place_postal_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('place_locality', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('place_country', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_events_place_id'), ['place_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_place_id'))
        batch_op.drop_column('place_country')
        batch_op.drop_column('place_locality')
        batch_op.drop_column('place_postal_code')
        batch_op.drop_column('place_route')
        batch_op.drop_column('place_street_number')
        batch_op.drop_column('place_price_level')
        batch_op.drop_column('place_maps_url')
        batch_op.drop_column('place_website')
        batch_op.drop_column('place_types')
        batch_op.drop_column('place_lng')
        batch_op.drop_column('place_lat')
        batch_op.drop_column('place_address')
        batch_op.drop_column('place_name')
        batch_op.drop_column('place_id')

    # ### end Alembic commands ###
