"""Convert funktion field from String to Enum

Revision ID: 24266bf7074b
Revises: 08673395767f
Create Date: 2025-09-10 08:01:30.590798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24266bf7074b'
down_revision = '08673395767f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
