"""Add fuehrerschein field to members table

Revision ID: 4701baf4d01d
Revises: e1eac5dbe270
Create Date: 2025-08-11 16:00:12.457605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4701baf4d01d'
down_revision = 'e1eac5dbe270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fuehrerschein', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('fuehrerschein')

    # ### end Alembic commands ###
