"""initial schema

Revision ID: 4b01776b2e01
Revises: 
Create Date: 2025-07-30 08:24:03.036460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b01776b2e01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('MEMBER', 'ADMIN', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('vorname', sa.String(length=100), nullable=False),
    sa.Column('nachname', sa.String(length=100), nullable=False),
    sa.Column('rufname', sa.String(length=100), nullable=True),
    sa.Column('geburtsdatum', sa.Date(), nullable=True),
    sa.Column('nationalitaet', sa.String(length=50), nullable=True),
    sa.Column('strasse', sa.String(length=200), nullable=True),
    sa.Column('hausnummer', sa.String(length=20), nullable=True),
    sa.Column('plz', sa.String(length=10), nullable=True),
    sa.Column('ort', sa.String(length=100), nullable=True),
    sa.Column('telefon', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('passwort_hash', sa.String(length=255), nullable=False),
    sa.Column('funktion', sa.String(length=100), nullable=True),
    sa.Column('vorstandsmitglied', sa.Boolean(), nullable=True),
    sa.Column('beitrittsjahr', sa.Integer(), nullable=True),
    sa.Column('koerpergroesse', sa.Integer(), nullable=True),
    sa.Column('schuhgroesse', sa.Float(), nullable=True),
    sa.Column('koerpergewicht', sa.Integer(), nullable=True),
    sa.Column('kleider_oberteil', sa.String(length=20), nullable=True),
    sa.Column('kleider_hosen', sa.String(length=20), nullable=True),
    sa.Column('kleider_cap', sa.String(length=20), nullable=True),
    sa.Column('zimmerwunsch', sa.String(length=200), nullable=True),
    sa.Column('spirit_animal', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_members_email'), ['email'], unique=True)

    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('LOGIN', 'READ_SENSITIVE_SELF', 'UPDATE_SENSITIVE_SELF', 'READ_SENSITIVE_OTHERS', 'UPDATE_SENSITIVE_OTHERS', 'DELETE_DOC_SOFT', 'DELETE_DOC_HARD', 'VIEW_MFA', 'ENABLE_MFA', 'DISABLE_MFA', 'USE_BACKUP_CODE', 'BILLBRO_COMPUTE', 'RSVP_UPDATE', 'EVENT_EDIT', 'ADMIN_CREATE_EVENT', 'ADMIN_CREATE_MEMBER', 'ADMIN_EDIT_MEMBER', name='auditaction'), nullable=False),
    sa.Column('entity', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('field', sa.String(length=100), nullable=True),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('extra_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisator_id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.DateTime(), nullable=False),
    sa.Column('event_typ', sa.Enum('ESSEN', 'AUSFLUG', name='eventtype'), nullable=False),
    sa.Column('restaurant', sa.String(length=200), nullable=True),
    sa.Column('kueche', sa.String(length=100), nullable=True),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('rechnungsbetrag_rappen', sa.Integer(), nullable=True),
    sa.Column('gesamtbetrag_rappen', sa.Integer(), nullable=True),
    sa.Column('trinkgeld_rappen', sa.Integer(), nullable=True),
    sa.Column('betrag_sparsam_rappen', sa.Integer(), nullable=True),
    sa.Column('betrag_normal_rappen', sa.Integer(), nullable=True),
    sa.Column('betrag_allin_rappen', sa.Integer(), nullable=True),
    sa.Column('weights_used_json', sa.JSON(), nullable=True),
    sa.Column('tip_rule', sa.String(length=50), nullable=True),
    sa.Column('rounding_rule', sa.String(length=50), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organisator_id'], ['members.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_datum'), ['datum'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_organisator_id'), ['organisator_id'], unique=False)

    op.create_table('member_mfa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('totp_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('is_totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('member_mfa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_member_mfa_member_id'), ['member_id'], unique=True)

    op.create_table('member_sensitive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('payload_encrypted', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('member_sensitive', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_member_sensitive_member_id'), ['member_id'], unique=True)

    op.create_table('mfa_backup_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'code_hash', name='uq_member_backup_code')
    )
    with op.batch_alter_table('mfa_backup_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mfa_backup_codes_member_id'), ['member_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('category', sa.Enum('VEREIN', 'EVENT', 'FOTO', 'STATUTEN', 'SONST', name='documentcategory'), nullable=False),
    sa.Column('visibility', sa.Enum('PUBLIC', 'MEMBER', 'ADMIN', name='documentvisibility'), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('uploader_id', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploader_id'], ['members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('teilnahme', sa.Boolean(), nullable=False),
    sa.Column('esstyp', sa.Enum('SPARSAM', 'NORMAL', 'ALLIN', name='esstyp'), nullable=True),
    sa.Column('guess_bill_amount_rappen', sa.Integer(), nullable=True),
    sa.Column('diff_amount_rappen', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('calculated_share_rappen', sa.Integer(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'event_id', name='uq_member_event')
    )
    with op.batch_alter_table('participations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participations_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_participations_member_id'), ['member_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participations_member_id'))
        batch_op.drop_index(batch_op.f('ix_participations_event_id'))

    op.drop_table('participations')
    op.drop_table('documents')
    with op.batch_alter_table('mfa_backup_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mfa_backup_codes_member_id'))

    op.drop_table('mfa_backup_codes')
    with op.batch_alter_table('member_sensitive', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_member_sensitive_member_id'))

    op.drop_table('member_sensitive')
    with op.batch_alter_table('member_mfa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_member_mfa_member_id'))

    op.drop_table('member_mfa')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_organisator_id'))
        batch_op.drop_index(batch_op.f('ix_events_datum'))

    op.drop_table('events')
    op.drop_table('audit_events')
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_members_email'))

    op.drop_table('members')
    # ### end Alembic commands ###
