"""Add Funktion enum to member model

Revision ID: b09d3e9b4b86
Revises: 5c8e2b9f3a12
Create Date: 2025-08-09 23:50:44.136825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b09d3e9b4b86'
down_revision = '5c8e2b9f3a12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh_key', sa.String(length=255), nullable=False),
    sa.Column('auth_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_subscriptions_member_id'), ['member_id'], unique=False)

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('funktion',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('MEMBER', 'PRAESIDENT', 'KOMMISSIONSPRAESIDENT', 'SCHATZMEISTER', 'MARKETINGKOMMISSAR', 'RECHNUNGSPRUEFER', name='funktion'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('funktion',
               existing_type=sa.Enum('MEMBER', 'PRAESIDENT', 'KOMMISSIONSPRAESIDENT', 'SCHATZMEISTER', 'MARKETINGKOMMISSAR', 'RECHNUNGSPRUEFER', name='funktion'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_subscriptions_member_id'))

    op.drop_table('push_subscriptions')
    # ### end Alembic commands ###
