"""Add GENERALVERSAMMLUNG to EventType enum

Revision ID: b8a4b3c5962b
Revises: 4eb0ce7550b7
Create Date: 2025-08-12 10:17:55.351824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8a4b3c5962b'
down_revision = '4eb0ce7550b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('event_typ',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('MONATSESSEN', 'AUSFLUG', 'GENERALVERSAMMLUNG', name='eventtype'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('event_typ',
               existing_type=sa.Enum('MONATSESSEN', 'AUSFLUG', 'GENERALVERSAMMLUNG', name='eventtype'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)

    # ### end Alembic commands ###
