"""Add event ratings table

Revision ID: ba05ea7e82ed
Revises: 21be0b09c373
Create Date: 2025-08-13 07:08:51.127983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba05ea7e82ed'
down_revision = '21be0b09c373'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('food_rating', sa.Integer(), nullable=False),
    sa.Column('drinks_rating', sa.Integer(), nullable=False),
    sa.Column('service_rating', sa.Integer(), nullable=False),
    sa.Column('highlights', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_ratings')
    # ### end Alembic commands ###
