"""Add password change and reset audit actions

Revision ID: e1eac5dbe270
Revises: b09d3e9b4b86
Create Date: 2025-08-11 11:44:13.827249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1eac5dbe270'
down_revision = 'b09d3e9b4b86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('event_typ',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('MONATSESSEN', 'AUSFLUG', name='eventtype'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('event_typ',
               existing_type=sa.Enum('MONATSESSEN', 'AUSFLUG', name='eventtype'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)

    # ### end Alembic commands ###
