"""Fix funktion enum conversion

Revision ID: e7215b9110a0
Revises: 24266bf7074b
Create Date: 2025-09-10 08:02:21.134966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7215b9110a0'
down_revision = '24266bf7074b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
