"""Add merch tables

Revision ID: e9f036101b2a
Revises: e7215b9110a0
Create Date: 2025-09-20 14:37:04.730586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9f036101b2a'
down_revision = 'e7215b9110a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merch_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_supplier_price_rappen', sa.Integer(), nullable=False),
    sa.Column('base_member_price_rappen', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merch_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('BESTELLT', 'WIRD_GELIEFERT', 'GELIEFERT', name='orderstatus'), nullable=False),
    sa.Column('total_member_price_rappen', sa.Integer(), nullable=False),
    sa.Column('total_supplier_price_rappen', sa.Integer(), nullable=False),
    sa.Column('total_profit_rappen', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('merch_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_merch_orders_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_merch_orders_order_number'), ['order_number'], unique=True)

    op.create_table('merch_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=False),
    sa.Column('supplier_price_rappen', sa.Integer(), nullable=False),
    sa.Column('member_price_rappen', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['merch_articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('merch_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_merch_variants_article_id'), ['article_id'], unique=False)

    op.create_table('merch_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_member_price_rappen', sa.Integer(), nullable=False),
    sa.Column('unit_supplier_price_rappen', sa.Integer(), nullable=False),
    sa.Column('total_member_price_rappen', sa.Integer(), nullable=False),
    sa.Column('total_supplier_price_rappen', sa.Integer(), nullable=False),
    sa.Column('total_profit_rappen', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['merch_articles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['merch_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['merch_variants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('merch_order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_merch_order_items_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_merch_order_items_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_merch_order_items_variant_id'), ['variant_id'], unique=False)

    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_agent', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('p256dh_key',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('auth_key',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.alter_column('auth_key',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('p256dh_key',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('is_active')
        batch_op.drop_column('user_agent')

    with op.batch_alter_table('merch_order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_merch_order_items_variant_id'))
        batch_op.drop_index(batch_op.f('ix_merch_order_items_order_id'))
        batch_op.drop_index(batch_op.f('ix_merch_order_items_article_id'))

    op.drop_table('merch_order_items')
    with op.batch_alter_table('merch_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_merch_variants_article_id'))

    op.drop_table('merch_variants')
    with op.batch_alter_table('merch_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_merch_orders_order_number'))
        batch_op.drop_index(batch_op.f('ix_merch_orders_member_id'))

    op.drop_table('merch_orders')
    op.drop_table('merch_articles')
    # ### end Alembic commands ###
